const GET_CAPSULES_SUCCESSFULLY = 'GET_CAPSULES_SUCCESSFULLY';
const GET_CAPSULES_FAILED = 'GET_CAPSULES_FAILED';
const GET_CREW_SUCCESSFULLY = 'GET_CREW_SUCCESSFULLY';
const GET_CREW_FAILED = 'GET_CREW_FAILED';
const GET_ROCKETS_SUCCESSFULLY = 'GET_ROCKETS_SUCCESSFULLY';
const GET_ROCKETS_FAILED = 'GET_ROCKETS_FAILED';
const GET_STARLINK_SUCCESSFULLY = 'GET_STARLINK_SUCCESSFULLY';
const GET_STARLINK_FAILED = 'GET_STARLINK_FAILED';

const ActionTypes = {
	GET_CAPSULES_SUCCESSFULLY,
	GET_CAPSULES_FAILED,
	GET_CREW_SUCCESSFULLY,
	GET_CREW_FAILED,
	GET_ROCKETS_SUCCESSFULLY,
	GET_ROCKETS_FAILED,
	GET_STARLINK_SUCCESSFULLY,
	GET_STARLINK_FAILED,
};

export default ActionTypes;
