const GET_CAPSULES_SUCCESSFULLY = 'GET_CAPSULES_SUCCESSFULLY';
const GET_CAPSULES_FAILED = 'GET_CAPSULES_FAILED';
const GET_CREW_SUCCESSFULLY = 'GET_CREW_SUCCESSFULLY';
const GET_CREW_FAILED = 'GET_CREW_FAILED';
const GET_ROCKETS_SUCCESSFULLY = 'GET_ROCKETS_SUCCESSFULLY';
const GET_ROCKETS_FAILED = 'GET_ROCKETS_FAILED';
const GET_STARLINK_SUCCESSFULLY = 'GET_STARLINK_SUCCESSFULLY';
const GET_STARLINK_FAILED = 'GET_STARLINK_FAILED';
const SHOW_MODAL = 'SHOW_MODAL';
const SET_CURRENT_POPUP_TITLE = 'SET_CURRENT_POPUP_TITLE';
const RESET_FETCH_STATES = 'RESET_FETCH_STATES';

const ActionTypes = {
	GET_CAPSULES_SUCCESSFULLY,
	GET_CAPSULES_FAILED,
	GET_CREW_SUCCESSFULLY,
	GET_CREW_FAILED,
	GET_ROCKETS_SUCCESSFULLY,
	GET_ROCKETS_FAILED,
	GET_STARLINK_SUCCESSFULLY,
	GET_STARLINK_FAILED,
	SHOW_MODAL,
	SET_CURRENT_POPUP_TITLE,
	RESET_FETCH_STATES,
};

export default ActionTypes;
